<!doctype html><html lang=en><head><meta name=generator content="Hugo 0.122.0"><script async src="https://www.googletagmanager.com/gtag/js?id=G-XSXMV79JL3"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag("js",new Date),gtag("config","G-XSXMV79JL3")</script><script type=text/javascript>(function(e,t,n,s,o,i,a){e[n]=e[n]||function(){(e[n].q=e[n].q||[]).push(arguments)},i=t.createElement(s),i.async=1,i.src="https://www.clarity.ms/tag/"+o,a=t.getElementsByTagName(s)[0],a.parentNode.insertBefore(i,a)})(window,document,"clarity","script","s1yeo4645e")</script><meta charset=UTF-8><meta name=viewport content="width=device-width,initial-scale=1"><title>Pinggy - Simple Localhost Tunnels
</title><link rel=icon type=image/x-icon href=/assets/favicon2.ico><link rel=stylesheet href=/css/style.min.css><link rel=stylesheet href=/css/syntax.min.css><link rel=stylesheet href=/css/customization.min.css><link rel=canonical href=https://pinggy.io/><meta property="og:locale" content="en_US"><meta property="og:type" content="website"><meta name=twitter:title content="Pinggy - Simple Localhost Tunnels"><meta property="og:title" content="Pinggy - Simple Localhost Tunnels"><meta name=description content="Pinggy is the simplest way to bring your localhost projects online. It the the fastest way to create secure tunnels to localhost with a public url."><meta property="og:description" content="Pinggy is the simplest way to bring your localhost projects online. It the the fastest way to create secure tunnels to localhost with a public url."><meta name=twitter:description content="Pinggy is the simplest way to bring your localhost projects online. It the the fastest way to create secure tunnels to localhost with a public url."><meta property="og:url" content="https://pinggy.io/"><meta property="og:site_name" content="Pinggy"><meta property="og:image" content="https://pinggy.io/assets/pinggy_og_img.jpg"><meta name=author content="Pinggy"><meta name=twitter:creator content="Pinggy"><meta name=twitter:card content="summary_large_image"><meta name=twitter:site content="@pinggyio"></head><body><nav class="navbar navbar-expand-lg fixed-top navbar-light"><div class="container py-2"><div class="logo navbar-brand"><a href=/><img height=50 src=/assets/pinggy_logo.webp alt="Pinggy brand logo"></a></div><button class=navbar-toggler type=button data-bs-toggle=collapse data-bs-target=#navbarSupportedContent aria-controls=navbarSupportedContent aria-expanded=false aria-label="Toggle navigation">
<span class=navbar-toggler-icon></span></button><div class="collapse navbar-collapse" id=navbarSupportedContent><ul class="navbar-nav mb-2 mb-lg-0"><li class="nav-item mx-2"><a class=nav-link aria-current=page href=/><span style=display:block data-bs-toggle=collapse data-bs-target=.navbar-collapse.show>Home</span></a></li><li class="nav-item mx-2"><a class=nav-link aria-current=page href=/#prices><span style=display:block data-bs-toggle=collapse data-bs-target=.navbar-collapse.show>Pricing</span></a></li><li class="nav-item mx-2"><a class=nav-link aria-current=page href=/docs/><span style=display:block data-bs-toggle=collapse data-bs-target=.navbar-collapse.show>Docs</span></a></li><li class="nav-item mx-2"><div class="nav-item dropdown"><a class="nav-link dropdown-toggle" href=# id=downloadDropdown role=button data-bs-toggle=dropdown aria-haspopup=true aria-expanded=false><span style=display:inline-block>Download</span></a><div class=dropdown-menu aria-labelledby=downloadDropdown><a class=dropdown-item href=/app/>GUI App</a>
<a class=dropdown-item href=/cli/>CLI</a>
<a target=_blank class=dropdown-item href=https://pinggy-io.github.io/sdk-nodejs/>Node.js SDK</a>
<a target=_blank class=dropdown-item href=https://pypi.org/project/pinggy/>Python SDK</a></div></li><li class="nav-item mx-2"><div class="nav-item dropdown"><a class="nav-link dropdown-toggle" href=# id=compareDropdown role=button data-bs-toggle=dropdown aria-haspopup=true aria-expanded=false><span style=display:inline-block>Compare</span></a><div class=dropdown-menu aria-labelledby=compareDropdown><a class=dropdown-item href=/compare/pinggy-vs-ngrok/>Pinggy vs Ngrok</a>
<a class=dropdown-item href=/compare/pinggy-vs-localxpose/>Pinggy vs Localxpose</a>
<a class=dropdown-item href=/compare/pinggy-vs-localtunnel/>Pinggy vs LocalTunnel</a>
<a class=dropdown-item href=/compare/pinggy-vs-cloudflare-tunnel/>Pinggy vs Cloudflare</a></div></div></li><li class="nav-item mx-2"><div class="nav-item dropdown"><a class="nav-link dropdown-toggle" href=# id=quickstartDropdown role=button data-bs-toggle=dropdown aria-haspopup=true aria-expanded=false><span style=display:inline-block>Use Cases</span></a><div class=dropdown-menu aria-labelledby=quickstartDropdown><a class=dropdown-item href=/ingress_for_dev_test_environments/>Ingress for dev/test</a>
<a class=dropdown-item href=/quickstart/>Quickstart recipes</a></div></div></li><li class="nav-item mx-2"><a class=nav-link aria-current=page href=/blog/><span style=display:block data-bs-toggle=collapse data-bs-target=.navbar-collapse.show>Blog</span></a></li><li class="nav-item mx-2"><div class="nav-item dropdown"><a class="nav-link dropdown-toggle" href=# id=helpDropdown role=button data-bs-toggle=dropdown aria-haspopup=true aria-expanded=false><span style=display:inline-block>Help</span></a><div class=dropdown-menu aria-labelledby=helpDropdown><a class=dropdown-item href=/help/>Help</a>
<a class=dropdown-item href=/help/#faq>FAQ</a></div></div></li><li class="nav-item mx-2"><a class=nav-link href=https://discord.gg/KX5DpTs3xx title=Discord target=_blank><span><svg xmlns="http://www.w3.org/2000/svg" style="width:1.4em" fill="currentcolor" class="bi bi-discord" viewBox="0 0 16 16"><path d="M13.545 2.907a13.227 13.227.0 00-3.257-1.011.05.05.0 00-.052.025c-.141.25-.297.577-.406.833a12.19 12.19.0 00-3.658.0 8.258 8.258.0 00-.412-.833.051.051.0 00-.052-.025c-1.125.194-2.22.534-3.257 1.011a.041.041.0 00-.021.018C.356 6.024-.213 9.047.066 12.032c.001.014.01.028.021.037a13.276 13.276.0 003.995 2.02.05.05.0 00.056-.019c.308-.42.582-.863.818-1.329a.05.05.0 00-.01-.059.051.051.0 00-.018-.011 8.875 8.875.0 01-1.248-.595.05.05.0 01-.02-.066.051.051.0 01.015-.019c.084-.063.168-.129.248-.195a.05.05.0 01.051-.007c2.619 1.196 5.454 1.196 8.041.0a.052.052.0 01.053.007c.08.066.164.132.248.195a.051.051.0 01-.004.085 8.254 8.254.0 01-1.249.594.05.05.0 00-.03.03.052.052.0 00.003.041c.24.465.515.909.817 1.329a.05.05.0 00.056.019 13.235 13.235.0 004.001-2.02.049.049.0 00.021-.037c.334-3.451-.559-6.449-2.366-9.106a.034.034.0 00-.02-.019zm-8.198 7.307c-.789.0-1.438-.724-1.438-1.612.0-.889.637-1.613 1.438-1.613.807.0 1.45.73 1.438 1.613.0.888-.637 1.612-1.438 1.612zm5.316.0c-.788.0-1.438-.724-1.438-1.612.0-.889.637-1.613 1.438-1.613.807.0 1.451.73 1.438 1.613.0.888-.631 1.612-1.438 1.612z"/></svg></span></a></li><li class="nav-item mx-2"><a class=nav-link href=https://forum.pinggy.io/ target=_blank><span><img title="Community Forum" src=/assets/pinggy_forum_logo.png alt="Pinggy Community Forum Logo" style=max-width:1.3em></span></a></li></ul><div class=nav-button><a href=https://dashboard.pinggy.io target=_blank id=LoginBtn class="p-2 mx-1">Dashboard</a></div></div></div></nav><header class="pt-1 contentcontainer" x-data="{ data : $store.advModal }" x-init="data.tryItYourself = JSON.parse(localStorage.getItem('tryItYourself')) || {
        selectedProtocol: 'HTTP',
        localaddress: 'localhost:8080',
        webdebugCheck: false,
        qrCheck: true
    };
    $watch('data.tryItYourself', function(value) {
        localStorage.setItem('tryItYourself', JSON.stringify(value));
    })"><div class=container><div class="alert alert-info p-1 text-center" role=alert>You can now use Pinggy <b>Node.js SDK</b> and <b>Python SDK</b> to create tunnels programmatically! <a href=/docs/ target=_blank>Learn more.</a> 🤯</div><div class="row justify-content-evenly"><div class=col-lg-5><div class="text-left my-5"><h1 class="display-5 fw-bolder biggestheader d-inline">Public URLs for Localhost.</h1><span class="mb-2 mt-2 fs-3 d-block">Without downloading any binary!</span><div class=mt-4 id=lead2>Create HTTP, TCP, UDP, or TLS tunnels to your Mac/PC.<br>Even if it is
sitting behind firewalls and NATs.</div><div style=margin-top:4em;max-width:28em><div style=font-weight:500><span class=highlight>&nbspFree persistent URL&nbsp;</span> for
7 days & custom domain support:
         </div><div class="input-group mt-1"><input type=email class=form-control placeholder=Email aria-label=Email aria-describedby=button-addon2 id=trialemail><div style=border-radius:.2em class=invalid-tooltip id=emailinvalidtooltip>Please enter a valid email</div><button style="border-color:#4775c6;background-color:#4675c7;padding:.6em 1em;box-shadow:0 0 4px #a3599b8c;font-weight:500" class="btn btn-secondary" type=button id=button-addon2 onclick=starttrial()>
Start 7 days free trial</button></div><button onclick=trynow() id=trynow>
Or just try it for free →</button></div></div></div><div class="col-lg-5 mt-5"><div class="text-left card" id=bigcodecolumn><div class=px-4><h2 class="h5 mt-3">Configure your free tunnel</h2><form class=mt-3><label for=localaddress class=text-bold><strong>Your local address:</strong></label><div class="input-group mt-2"><div class=input-group-prepend><select class=form-select id=protocolSelect x-model=data.tryItYourself.selectedProtocol aria-label="Select protocol"><option value=HTTP>HTTP</option><option value=TCP>TCP</option><option value=UDP>UDP</option></select></div><input class=form-control id=localaddress type=text :placeholder="data.tryItYourself.localaddress || 'localhost:8000'" x-model=data.tryItYourself.localaddress aria-label="Local address"></div></form><div class="mt-3 row"><div class=col-md-6><label class=switch aria-label="Web Debugger"><input type=checkbox id=webdebuggerinput x-model=data.tryItYourself.webdebugCheck>
<span class="slider round"></span>
</label><span class="align-middle enablewebdebuglabel">Web Debugger</span></div><div class=col-md-6><label class=switch aria-label="QR Code"><input type=checkbox id=qrinput x-model=data.tryItYourself.qrCheck>
<span class="slider round"></span>
</label><span class="align-middle enablewebdebuglabel">QR Code
<i class="bi bi-info-circle" data-bs-toggle=tooltip data-bs-placement=right data-bs-html=true title="Show QR Code for the URL"></i></span></div></div><div class="alert alert-warning mt-3 mb-0" x-show=$store.advModal.getError() x-text=$store.advModal.getError() role=alert>A simple warning alert—check it out!</div></div><div id=finalcommand class="border-top mt-3 px-4 py-3"><label class="text-bold mt-2" x-show="data.tryItYourself.selectedProtocol == 'UDP'"><strong>First Download the <a target=_blank href=/cli/>Pinggy CLI</a></strong><br></label><label class="text-bold mt-2"><strong>Paste this command to start tunnel:</strong></label><div class="input-group mt-2"><textarea id=portcommand class=form-control aria-label="Command to start tunnel" readonly x-text=$store.advModal.tryItYourselfCommand()></textarea>
<button class="btn btn-dark" type=button id=copybutton_tryityourselfcommand aria-label="Copy SSH URL to Clipboard" onclick='copytoclipboard(this,"#portcommand")'>
<i class="bi bi-clipboard"></i></button></div><div class=mt-2 id=instructions>Enter "yes" to continue connecting. Enter blank password if
prompted.</div><div class=mt-2 id=webdebugurl x-show=data.tryItYourself.webdebugCheck>Default Web Debugger URL:
<a href=http://localhost:4300 target=_blank>http://localhost:4300</a></div><div class=mt-3><button type=button class="ml-1 btn btn-light text-decoration-none float-end border" data-bs-toggle=modal data-bs-target=#advancedModal id=advancedModalButton>
<i class="bi bi-gear"></i> Advanced Settings
<i class="bi bi-chevron-right" style=font-size:.8rem></i>
</button>
<a href=/docs/ target=_blank type=button class="mx-1 btn btn-light text-decoration-none float-end border"><i class="bi bi-file-text"></i> Docs
<i class="bi bi-chevron-right" style=font-size:.8rem></i></a></div></div></div></div></div></div></header><div class="modal fade" id=advancedModal tabindex=-1 aria-labelledby=advancedModalLabel aria-hidden=true x-data="{ data : $store.advModal }" x-init="$watch('data.httpConfig', function(value) {
        localStorage.setItem('httpConfig', JSON.stringify(value));
    }, { deep: true });    
    $watch('data.tcp_tlsConfig', function(value) {
        localStorage.setItem('tcp_tlsConfig', JSON.stringify(value));
    }, { deep: true });"><div class="modal-dialog modal-lg"><div class="modal-content px-2 pb-3"><div class=modal-header><span class=modal-title id=advancedModalLabel>Advanced Tunnel Configuration</span>
<button type=button class=btn-close data-bs-dismiss=modal aria-label=Close></button></div><div class="modal-body pt-4"><div class=mb-3 x-data="{
    data: { tunnelString: 'Paste this command to start tunnel:',
        portString: 'Local Port',
        localPort: '8000',
        webDebugPort: '4300',
        webDebugEnabled: true,
        keepAlive: true,
        passwordCheck: false,
        basicusername: '',
        basicpass: '',
        qrCheck: false,
        reconnect: false,
        connectiontype: 'ssh',
        platformselect: 'unix',
        manuallyCheckKey: false,
        mode: 'http',
        keyAuthentication: false,
        keyAuthentications: [],
        ipWhitelistCheck: false,
        ipWhitelist: [],
        headerModifications: [],
        localServerTLS: false,
        localServerTLSSNI: '',
        noReverseProxy: false,
        httpsonly: false,
        forwardHost: false,
        forwardHostAddress: '127.0.0.1',
        force: false,
        corsPreflight: false,
        xForwardedFor: false,
        fullUrl: false,
        accesstoken: false,
        accesstokenvalue: ''
    }
  }" x-init="data.platformselect = getOS() == 'windows' ? 'windows_powershell' : 'unix'"><div class=pinggytunnelshortcode data-headermodifications=[] data-mode=http><ul class="nav nav-tabs" id=myTab role=tablist><li class=nav-item role=presentation><button class="nav-link active" id=http-tab data-bs-toggle=tab data-bs-target=#tab-pane type=button role=tab aria-controls=http-tab-pane aria-selected=true @click="data.mode = 'http'">HTTP(S)</button></li><li class=nav-item role=presentation><button class=nav-link id=tcp-tab data-bs-toggle=tab data-bs-target=#tab-pane type=button role=tab aria-controls=tcp-tab-pane aria-selected=false @click="data.mode = 'tcp'">TCP</button></li><li class=nav-item role=presentation><button class=nav-link id=tls-tab data-bs-toggle=tab data-bs-target=#tab-pane type=button role=tab aria-controls=tls-tab-pane aria-selected=false @click="data.mode = 'tls'">TLS</button></li><li class=nav-item role=presentation><button class=nav-link id=udp-tab data-bs-toggle=tab data-bs-target=#tab-pane type=button role=tab aria-controls=udp-tab-pane aria-selected=false @click="data.mode = 'udp'">UDP</button></li></ul><div class="pinggytunnelshortcode_formwrapper tab-pane fade show active" id=tab-pane><form><div class="d-flex justify-content-sm-start justify-content-md-end gap-2" style=width:100%;margin-top:8px><div class=dropdown><div class="btn btn-sm dropdown-toggle" style=background-color:#2b3039;border-radius:4px;color:#fff;font-size:.75rem role=button id=dropdownMenuButtonConnectionType data-bs-toggle=dropdown aria-expanded=false x-text="data.mode === 'udp' ? 'CLI' : (data.connectiontype === 'ssh' ? 'SSH' : 'CLI')"></div><div x-show="data.mode !== 'udp'" class=dropdown-menu aria-labelledby=dropdownMenuButtonConnectionType><span class=dropdown-item x-on:click="data.connectiontype = 'ssh'" style=cursor:pointer>SSH</span>
<span class=dropdown-item x-on:click="data.connectiontype = 'cli'" style=cursor:pointer>CLI</span></div></div><div class=dropdown><div class="btn btn-sm dropdown-toggle" style=background-color:#2b3039;border-radius:4px;color:#fff;font-size:.75rem role=button id=dropdownMenuButtonPlatform data-bs-toggle=dropdown aria-expanded=false x-text="data.platformselect === 'unix' ? 'Mac / Linux' : data.platformselect === 
                'windows_powershell' ? 'Windows Powershell' : 'Windows CMD'"></div><div class=dropdown-menu aria-labelledby=dropdownMenuButtonPlatform><span class=dropdown-item x-on:click="data.platformselect = 'unix'" style=cursor:pointer>Mac / Linux</span>
<span class=dropdown-item x-on:click="data.platformselect = 'windows_powershell'" style=cursor:pointer>Windows Powershell</span>
<span class=dropdown-item x-on:click="data.platformselect = 'windows_cmd'" style=cursor:pointer>Windows CMD</span></div></div></div><label class=text-bold><strong x-text=data.tunnelString></strong></label><div class="input-group mt-1"><textarea style=background:#fafaff;font-size:.9rem class="form-control font-monospace pinggytunnelshortcode_advancedcommand" :rows="data.reconnect ? 3 : 2" x-text=$store.pinggyTunnelData.advancedCommand(data) readonly></textarea>
<button class="btn btn-outline-dark pinggytunnelshortcode_copybutton" type=button>
<i class="bi bi-clipboard"></i></button></div><template x-if="data.mode === 'http'"><div class="mt-3 shortcode_webdebugurl" x-show=data.webDebugEnabled x-transition.duration.300ms style=font-size:.8rem x-html="'Web Debugger URL: <a href=http://localhost:' + data.webDebugPort + ' target=_blank>http://localhost:' + data.webDebugPort + '</a>'"></div></template><div class="alert alert-warning mt-2 p-2 shortcode_alert" style=font-size:.9rem role=alert id=shortcode_alert_81dc4b8cedcc844cefabcc6d2f5fda54 x-show="data.reconnect && (data.connectiontype === 'ssh')" x-transition.duration.300ms>When the tunnel reconnects, your public URL will change. Upgrade to
<a href=/#prices>Pinggy Pro</a> for persistent URLs.</div><hr><label class=text-bold><strong>Settings:</strong></label><div class="row mt-2"><div class="col col-12 col-lg-6"><div class="form-floating mb-3"><input type=number class="form-control shortcode_localPort" id=shortcode_localPort_81dc4b8cedcc844cefabcc6d2f5fda54 x-model=data.localPort :placeholder=data.portString>
<label for=shortcode_localPort_81dc4b8cedcc844cefabcc6d2f5fda54 x-text=data.portString></label></div></div><div class="col col-12 col-lg-6"><div class="form-floating mb-3"><select class=form-select id=shortcode_regionselect x-model=data.selectedRegion><option value=free.pinggy.io>Auto</option><option value=us.free.pinggy.io>USA</option><option value=eu.free.pinggy.io>Europe</option><option value=ap.free.pinggy.io>Asia</option></select>
<label for=shortcode_regionselect id=shortcode_regionselector>Region</label></div></div></div><div class=row><div class="col col-12 col-lg-6" x-show="data.mode === 'http'"><div class="form-check form-switch mb-3"><input class="form-check-input shortcode_passwordCheck" id=shortcode_passwordCheck_81dc4b8cedcc844cefabcc6d2f5fda54 type=checkbox x-on:click="data.keyAuthentication = false" x-model=data.passwordCheck>
<label class=form-check-label for=shortcode_passwordCheck_81dc4b8cedcc844cefabcc6d2f5fda54>Password Protect
<i class="bi bi-info-circle" type=button data-bs-toggle=tooltip data-bs-placement=right data-bs-html=true title="Enable basic authentication"></i></label></div></div><div class="col col-12 col-lg-6" x-show="data.mode === 'http'"><div class="form-check form-switch mb-3"><input class="form-check-input shortcode_qrcheck" type=checkbox id=shortcode_qrcheck_81dc4b8cedcc844cefabcc6d2f5fda54 x-model=data.qrCheck>
<label class=form-check-label for=shortcode_qrcheck_81dc4b8cedcc844cefabcc6d2f5fda54>QR Code
<i class="bi bi-info-circle" type=button data-bs-toggle=tooltip data-bs-placement=right data-bs-html=true title="Show QR Code for the URL"></i></label></div></div><template x-if="data.passwordCheck && (data.mode === 'http')"><div class="row shortcode_passwordfields"><div class="col col-12 col-lg-6"><div class="form-floating mb-3"><input class="form-control shortcode_basicusername" :class="{'is-invalid' : data.basicusername.includes(':')}" id=shortcode__basicusername_81dc4b8cedcc844cefabcc6d2f5fda54 placeholder=Username x-model=data.basicusername><div class=invalid-feedback x-show="data.basicusername.includes(':')">Username cannot contain ':'</div><label for=shortcode_basicusername_81dc4b8cedcc844cefabcc6d2f5fda54>Username</label></div></div><div class="col col-12 col-lg-6"><div class="form-floating mb-3"><input class="form-control shortcode_basicpass" :class="{'is-invalid' : data.basicpass.includes(':')}" id=shortcode_basicpass_81dc4b8cedcc844cefabcc6d2f5fda54 placeholder=Password x-model=data.basicpass><div class=invalid-feedback x-show="data.basicpass.includes(':')">Password cannot contain ':'</div><label for=shortcode_basicpass_81dc4b8cedcc844cefabcc6d2f5fda54>Password</label></div></div></div></template><div class="col col-12 col-lg-6" x-show="data.connectiontype != 'cli'"><div class="form-check form-switch mb-3"><input class="form-check-input shortcode_keepalive" id=shortcode_keepalive_81dc4b8cedcc844cefabcc6d2f5fda54 type=checkbox x-model=data.keepAlive>
<label class=form-check-label for=shortcode_keepalive_81dc4b8cedcc844cefabcc6d2f5fda54>Keep Alive
<i class="bi bi-info-circle" type=button data-bs-toggle=tooltip data-bs-placement=right title="Send keep alive packets for a stable tunnel"></i></label></div></div><div class="col col-12 col-lg-6" x-show="data.connectiontype != 'cli'"><div class="form-check form-switch mb-3"><input class="form-check-input shortcode_restart" type=checkbox id=shortcode_restart_81dc4b8cedcc844cefabcc6d2f5fda54 x-model=data.reconnect>
<label class=form-check-label for=shortcode_restart_81dc4b8cedcc844cefabcc6d2f5fda54>Auto Reconnect
<i class="bi bi-info-circle" type=button data-bs-toggle=tooltip data-bs-placement=right title="Automatically reconnect tunnel on failure."></i></label></div></div><div class="col col-12 col-lg-6" x-show="data.mode === 'http'"><div class="form-check form-switch mb-3"><input class="form-check-input shortcode_webdebugCheck" type=checkbox id=shortcode_webdebugCheck_81dc4b8cedcc844cefabcc6d2f5fda54 x-model=data.webDebugEnabled>
<label class=form-check-label for=shortcode_webdebugCheck_81dc4b8cedcc844cefabcc6d2f5fda54>Web Debugger</label></div></div><div class="col col-12 col-lg-6" x-show="data.connectiontype != 'cli'" x-transition.duration.150ms><div class="form-check form-switch mb-3"><input class="form-check-input shortcode_rsaCheck" type=checkbox id=shortcode_rsaCheck_81dc4b8cedcc844cefabcc6d2f5fda54 x-model=data.manuallyCheckKey>
<label class=form-check-label for=shortcode_rsaCheck_81dc4b8cedcc844cefabcc6d2f5fda54>Manually check host key
<i class="bi bi-info-circle" type=button data-bs-toggle=tooltip data-bs-placement=right title="Type 'yes' to manually validate host key"></i></label></div></div><div class="col col-12 col-lg-6" x-show="data.mode !== 'http'"><div class="form-check form-switch mb-3"><input class="form-check-input shortcode_ipWhitelistCheck" type=checkbox id=adv_ipWhitelist x-model=data.ipWhitelistCheck>
<label class=form-check-label for=shortcode_ipWhitelistCheck_81dc4b8cedcc844cefabcc6d2f5fda54>IP Whitelist
<i class="bi bi-info-circle" type=button data-bs-toggle=tooltip data-bs-placement=right title="Allow specified IPs to access the tunnel"></i></label></div><div class="col col-12" x-show=data.ipWhitelistCheck x-transition.duration.300ms><div id=ipwhitelistinputcontainer><div class="input-group ipwhitelistgroup"><input type=text aria-label="ip to whitelist" :class="{'is-invalid' : data.ipWhitelist[0] 
                        && ipCidrValidator(data.ipWhitelist[0]) === false}" placeholder="IP in CIDR (e.g. 10.2.3.4/16)" class="form-control ipval" x-model.debounce.500ms=data.ipWhitelist[0]>
<button class="btn btn-outline-dark addipinput" type=button @click="data.ipWhitelist.push('')">
<i class="bi bi-plus"></i></button><div class=invalid-feedback x-show="data.ipWhitelist[0] && ipCidrValidator(data.ipWhitelist[0]) === false">Invalid CIDR Format</div></div><template x-for="(ip, index) in data.ipWhitelist" :key=index><div x-show="index > 0" class="input-group ipwhitelistgroup"><input type=text aria-label="ip to whitelist" :class="{'is-invalid' : data.ipWhitelist[index] 
                            && ipCidrValidator(data.ipWhitelist[index]) === false}" placeholder="IP in CIDR (e.g. 10.2.3.4/16)" class="form-control ipval" x-model.debounce.500ms=data.ipWhitelist[index]>
<button class="btn btn-outline-danger removeipinput" type=button @click="data.ipWhitelist.splice(index, 1)">
<i class="bi bi-x"></i></button><div class=invalid-feedback x-show="data.ipWhitelist[index] && ipCidrValidator(data.ipWhitelist[index]) === false">Invalid CIDR Format</div></div></template></div></div></div><div class="col col-12 col-lg-6" x-show="data.mode === 'http'"><div class="form-check form-switch mb-3"><input class="form-check-input shortcode_keyAuthentication" type=checkbox id=adv_keyAuthentication x-model=data.keyAuthentication x-on:click="data.passwordCheck = false">
<label class=form-check-label for=shortcode_keyAuthentication_81dc4b8cedcc844cefabcc6d2f5fda54>Key / Token Authentication
<i class="bi bi-info-circle" type=button data-bs-toggle=tooltip data-bs-placement=right title="Bearer token authentication"></i></label></div><div class="col col-12 mb-3" x-show=data.keyAuthentication x-transition.duration.300ms><div id=keyauthinputcontainer><div class="input-group keyauthgroup"><input type=text aria-label="key / token" placeholder="Key / token" class="form-control keyauthval" x-model=data.keyAuthentications[0]>
<button class="btn btn-outline-dark addkeyauthinput" type=button @click="data.keyAuthentications.push('')">
<i class="bi bi-plus"></i></button></div><template x-for="(keyauth, index) in data.keyAuthentications" :key=index><div x-show="index > 0" class="input-group keyauthgroup"><input type=text aria-label="key / token" placeholder="Key / token" class="form-control keyauthval" x-model=data.keyAuthentications[index]>
<button class="btn btn-outline-danger removekeyauthinput" type=button @click="data.keyAuthentications.splice(index, 1)">
<i class="bi bi-x"></i></button></div></template></div></div></div><div class="col col-12 col-lg-6" x-show="data.mode === 'http'"><div class="form-check form-switch mb-3"><input class="form-check-input shortcode_ipWhitelistCheck" type=checkbox id=adv_ipWhitelist x-model=data.ipWhitelistCheck>
<label class=form-check-label for=shortcode_ipWhitelistCheck_81dc4b8cedcc844cefabcc6d2f5fda54>IP Whitelist
<i class="bi bi-info-circle" type=button data-bs-toggle=tooltip data-bs-placement=right title="Allow specified IPs to access the tunnel"></i></label></div><div class="col col-12 mb-3" x-show=data.ipWhitelistCheck x-transition.duration.300ms><div id=ipwhitelistinputcontainer><div class="input-group ipwhitelistgroup"><input type=text aria-label="ip to whitelist" :class="{'is-invalid' : data.ipWhitelist[0] 
                        && ipCidrValidator(data.ipWhitelist[0]) === false}" placeholder="IP in CIDR (e.g. 10.2.3.4/16)" class="form-control ipval" x-model.debounce.500ms=data.ipWhitelist[0]>
<button class="btn btn-outline-dark addipinput" type=button @click="data.ipWhitelist.push('')">
<i class="bi bi-plus"></i></button><div class=invalid-feedback x-show="data.ipWhitelist[0] && ipCidrValidator(data.ipWhitelist[0]) === false">Invalid CIDR Format</div></div><template x-for="(ip, index) in data.ipWhitelist" :key=index><div x-show="index > 0" class="input-group ipwhitelistgroup"><input type=text aria-label="ip to whitelist" :class="{'is-invalid' : data.ipWhitelist[index] 
                            && ipCidrValidator(data.ipWhitelist[index]) === false}" placeholder="IP in CIDR (e.g. 10.2.3.4/16)" class="form-control ipval" x-model.debounce.500ms=data.ipWhitelist[index]>
<button class="btn btn-outline-danger removeipinput" type=button @click="data.ipWhitelist.splice(index, 1)">
<i class="bi bi-x"></i></button><div class=invalid-feedback x-show="data.ipWhitelist[index] && ipCidrValidator(data.ipWhitelist[index]) === false">Invalid CIDR Format</div></div></template></div></div></div><div class="col col-12 col-lg-6" x-show="data.mode === 'http'"><div class="form-check form-switch mb-3"><input class="form-check-input shortcode_httpsonly" type=checkbox id=adv_httpsonly_81dc4b8cedcc844cefabcc6d2f5fda54 x-model=data.httpsonly>
<label class=form-check-label for=shortcode_httpsonly_81dc4b8cedcc844cefabcc6d2f5fda54>HTTPS only
<i class="bi bi-info-circle" type=button data-bs-toggle=tooltip data-bs-placement=right title="Only allow HTTPS requests"></i></label></div></div><div class="col col-12 col-lg-6"><div class="form-check form-switch mb-3"><input class="form-check-input shortcode_forwardhost" type=checkbox id=adv_forwardhost_81dc4b8cedcc844cefabcc6d2f5fda54 x-model=data.forwardHost>
<label class=form-check-label for=shortcode_forwardhost_81dc4b8cedcc844cefabcc6d2f5fda54>Forward to other hosts
<i class="bi bi-info-circle" type=button data-bs-toggle=tooltip data-bs-placement=right title="Forwarding to addresses other than localhost"></i></label></div><div class="col col-12 mb-3" x-show=data.forwardHost x-transition.duration.300ms><input type=text aria-label="forward to other hosts" placeholder=Address class="form-control forwardhostval" x-model=data.forwardHostAddress></div></div><div class="col col-12 col-lg-6" x-show="data.mode === 'http'"><div class="form-check form-switch mb-3"><input class="form-check-input shortcode_localServerTLS" type=checkbox id=adv_localServerTLS x-model=data.localServerTLS>
<label class=form-check-label for=shortcode_accesstoken_81dc4b8cedcc844cefabcc6d2f5fda54>Connect to HTTPS Server
<i class="bi bi-info-circle" type=button data-bs-toggle=tooltip data-bs-placement=right title="Connect to an HTTPS(TLS) server running locally"></i></label></div><div class="col col-12 mb-3" x-show=data.localServerTLS x-transition.duration.300ms><input type=text aria-label=localServerTLS placeholder="Local Server Name (SNI)" class="form-control localServerTLSval" x-model=data.localServerTLSSNI></div></div><div class="col col-12 col-lg-6" x-show="data.mode === 'http'"><div class="form-check form-switch mb-3"><input class="form-check-input shortcode_noReverseProxy" type=checkbox id=adv_noReverseProxy_81dc4b8cedcc844cefabcc6d2f5fda54 x-model=data.noReverseProxy>
<label class=form-check-label for=shortcode_noReverseProxy_81dc4b8cedcc844cefabcc6d2f5fda54>No Reverse Proxy
<i class="bi bi-info-circle" type=button data-bs-toggle=tooltip data-bs-placement=right title="Disable reverse proxy headers"></i></label></div></div><div class="col col-12 col-lg-6"><div class="form-check form-switch mb-3"><input class="form-check-input shortcode_force" type=checkbox id=shortcode_force_81dc4b8cedcc844cefabcc6d2f5fda54 x-model=data.force>
<label class=form-check-label for=shortcode_force_81dc4b8cedcc844cefabcc6d2f5fda54>Force
<i class="bi bi-info-circle" type=button data-bs-toggle=tooltip data-bs-placement=right data-bs-html=true title="Forcefully close existing tunnels and establish a new tunnel"></i></label></div></div><div class="col col-12 col-lg-6" x-show="data.mode === 'http'"><div class="form-check form-switch mb-3"><input class="form-check-input shortcode_corsPreflight" type=checkbox id=shortcode_corsPreflight_81dc4b8cedcc844cefabcc6d2f5fda54 x-model=data.corsPreflight>
<label class=form-check-label for=shortcode_corsPreflight_81dc4b8cedcc844cefabcc6d2f5fda54>Allow CORS preflight
<i class="bi bi-info-circle" type=button data-bs-toggle=tooltip data-bs-placement=right data-bs-html=true title="Key authentication / password authentication will block
                  all unauthenticated requests to Pinggy URLs. To allow
                  CORS preflight requests, enable this option."></i></label></div></div><div class="col col-12 col-lg-6" x-show="data.mode === 'http'"><div class="form-check form-switch mb-3"><input class="form-check-input shortcode_xForwardedFor" type=checkbox id=shortcode_xForwardedFor_81dc4b8cedcc844cefabcc6d2f5fda54 x-model=data.xForwardedFor>
<label class=form-check-label for=shortcode_xForwardedFor_81dc4b8cedcc844cefabcc6d2f5fda54>X-Forwarded-For header
<i class="bi bi-info-circle" type=button data-bs-toggle=tooltip data-bs-placement=right data-bs-html=true title="Add X-Forwarded-For header to every request"></i></label></div></div><div class="col col-12 col-lg-6" x-show="data.mode === 'http'"><div class="form-check form-switch mb-3"><input class="form-check-input shortcode_fullUrl" type=checkbox id=shortcode_fullUrl_81dc4b8cedcc844cefabcc6d2f5fda54 x-model=data.fullUrl>
<label class=form-check-label for=shortcode_fullUrl_81dc4b8cedcc844cefabcc6d2f5fda54>Original request url header
<i class="bi bi-info-circle" type=button data-bs-toggle=tooltip data-bs-placement=right data-bs-html=true title="Original uri for every request in X-Pinggy-Url header"></i></label></div></div><div class="col col-12 col-lg-6"><div class="form-check form-switch mb-3"><input class="form-check-input shortcode_accesstoken" type=checkbox id=adv_accesstoken x-model=data.accesstoken>
<label class=form-check-label for=shortcode_accesstoken_81dc4b8cedcc844cefabcc6d2f5fda54>Use Token
<i class="bi bi-info-circle" type=button data-bs-toggle=tooltip data-bs-placement=right title="Use your Pinggy token"></i></label></div><div class="col col-12 mb-2" x-show=data.accesstoken x-transition.duration.300ms><input type=text aria-label=token placeholder="Access Token" :class="{'is-invalid': /[^a-zA-Z0-9-]/.test(data.accesstokenvalue)}" class="form-control accesstokenval" x-model=data.accesstokenvalue><div class=invalid-feedback x-show="/[^a-zA-Z0-9-]/.test(data.accesstokenvalue) === true">Alphanumeric characters only</div></div></div></div><div class="row mt-2" style=--bs-gutter-x:0 x-show="data.mode === 'http'"><div class="form-floating mb-3 shortcode_webdebuggerportselector col" id=shortcode_webdebuggerportselector_81dc4b8cedcc844cefabcc6d2f5fda54 x-show=data.webDebugEnabled x-transition.duration.300ms><input type=number class="form-control shortcode_webdebugPort" id=shortcode_webdebugPort_81dc4b8cedcc844cefabcc6d2f5fda54 :placeholder=data.webDebugPort x-model=data.webDebugPort>
<label for=shortcode_webdebugPort_81dc4b8cedcc844cefabcc6d2f5fda54>Web Debugger Port</label></div></div><div x-show="data.mode === 'http'"><label class=form-check-label>Live Header Modifications
<i class="bi bi-info-circle" type=button data-bs-toggle=tooltip data-bs-placement=right data-bs-html=true title="Change request headers on the fly - <a href='/docs/advanced/live_header/' target='_blank'>read more.</a>"></i></label><div><button type=button class="btn btn-primary mb-3 mt-2 custom-button" @click="data.headerModifications.push({ mode: 'a', headername: '', headerval: '' })">
<i class="bi bi-plus"></i> Add header modification rule</button></div><div class=headermodificationcontainer><template x-for="(headerMod, index) in data.headerModifications" :key=index><div class="input-group shortcode_headermodificationgroup"><select class="form-select shortcode_headermodificationmode" x-model=data.headerModifications[index].mode><option value=a>Add</option><option value=u>Replace</option><option value=r>Remove</option></select>
<input type=text aria-label="header name" placeholder="Header Name" class="form-control shortcode_headername" x-model=data.headerModifications[index].headername>
<input type=text aria-label="header value" placeholder=Value class="form-control shortcode_headerval" x-model=data.headerModifications[index].headerval :disabled="data.headerModifications[index].mode === 'r'" :value="data.headerModifications[index].mode === 'r' ? '' : data.headerModifications[index].headerval">
<button class="btn btn-outline-danger shortcode_removeheadermodificationrow" type=button @click="data.headerModifications.splice(index, 1)">
<i class="bi bi-x"></i></button></div></template></div></div></form></div></div></div></div></div></div></div><style>.termgif-terminal{border:1px solid #e0e0e0;border-radius:10px;padding:0;max-width:600px;min-height:340px;box-shadow:0 8px 32px rgba(60,60,60,.1),0 1.5px 6px rgba(60,60,60,8%);margin:0 auto;overflow:hidden;display:flex;flex-direction:column;justify-content:flex-start}.termgif-header{display:flex;align-items:center;padding:0 16px;height:32px;background:linear-gradient(180deg,#ECECEC 0%,#D8D8D8 100%);border-top-left-radius:8px;border-top-right-radius:8px;box-shadow:0 1px #B0B0B0;position:relative}.termgif-dots{display:flex;gap:8px;position:absolute;left:16px;top:50%;transform:translateY(-50%)}.termgif-dot{width:10px;height:10px;border-radius:50%;border:1px solid #bbb;box-shadow:0 1px 2px rgba(0,0,0,.12)}.termgif-dot.red{background-color:#ff5f56;border-color:#e0443e}.termgif-dot.yellow{background-color:#ffbd2e;border-color:#dea123}.termgif-dot.green{background-color:#27c93f;border-color:#13a10e}.termgif-content{padding:18px 16px 10px;color:#f8f8f2;font-size:15px;font-family:menlo,monaco,courier new,Courier,monospace;background:0 0;background-color:#272822;min-height:330px}.termgif-step{opacity:0;animation:fadeIn .5s forwards;font-family:menlo,monaco,courier new,Courier,monospace;font-size:15px;color:#f8f8f2;letter-spacing:.5px;line-height:1.6;font-family:menlo,monaco,courier new,Courier,monospace}@keyframes fadeIn{to{opacity:1}}.blink{animation:blink 1s step-end infinite;color:#f1f1f1}@keyframes blink{50%{opacity:0}}.monokai-green{color:#a6e22e}.monokai-pink{color:#f92672}.monokai-yellow{color:#e6db74}.monokai-blue{color:#66d9ef}.monokai-orange{color:#fd971f}</style><div class=container><div class="pt-5 my-3 row justify-content-center"><div class=col-lg-5><h2 class="h4 mt-5 mb-5 text-left fw-light">Quickest way to <span id=textchanger></span></h2><section id=features><div class=container><div class=marquee><div class=marquee-content><a href=quickstart/jupyternotebook/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/jupyter.svg alt=jupyter>
</a><a href=quickstart/django/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/django.svg alt=django>
</a><a href=quickstart/apachehttpd/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/apache.svg alt=apache>
</a><a href=quickstart/drupal/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/drupal.svg alt=drupal>
</a><a href=quickstart/flask/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/flask.svg alt=flask>
</a><a href=quickstart/github/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/github.svg alt=github>
</a><a href=quickstart/gitlab/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/gitlab.svg alt=gitlab>
</a><a href=quickstart/joomla/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/joomla.svg alt=joomla>
</a><a href=quickstart/laravel/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/laravel.svg alt=laravel>
</a><a href=quickstart/mongodb/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/mongodb.svg alt=mongodb>
</a><a href=quickstart/mysql/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/mysql.svg alt=mysql>
</a><a href=quickstart/mssql/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/mssql.svg alt=mssql>
</a><a href=quickstart/nuxt/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/nuxt.svg alt=nuxt>
</a><a href=quickstart/nginx/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/nginx.svg alt=nginx>
</a><a href=quickstart/postgresql/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/postgresql.svg alt=postgresql>
</a><a href=quickstart/redis/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/redis.svg alt=redis>
</a><a href=quickstart/wordpress/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/wordpress.svg alt=wordpress>
</a><a href=quickstart/xampp/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/xampp.svg alt=xampp>
</a><a href=quickstart/ghost/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/ghost.svg alt=ghost>
</a><a href=quickstart/homeassistant/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/homeassistant.svg alt=homeassistant>
</a><a href=quickstart/shopify/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/shopify.svg alt=shopify>
</a><a href=quickstart/razorpay/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/razorpay.svg alt=razorpay>
</a><a href=quickstart/traefik/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/traefik.svg alt=traefik>
</a><a href=quickstart/portainer/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/portainer.svg alt=portainer>
</a><a href=quickstart/slack/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/slack.svg alt=slack>
</a><a href=quickstart/stripe/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/stripe.svg alt=stripe>
</a><a href=quickstart/wamp/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/wamp.svg alt=wamp>
</a><a href=quickstart/rails/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/rails.svg alt=rails>
</a><a href=quickstart/react/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/react.svg alt=react>
</a><a href=quickstart/svelte/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/svelte.svg alt=svelte>
</a><a href=quickstart/next/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/next.svg alt=next>
</a><a href=quickstart/express/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/express.svg alt=express>
</a><a href=quickstart/springboot/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/springboot.svg alt=springboot>
</a><a href=quickstart/nextcloud/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/nextcloud.svg alt=nextcloud>
</a><a href=quickstart/twilio/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/twilio.svg alt=twilio>
</a><a href=quickstart/telegram/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/telegram.svg alt=telegram>
</a><a href=quickstart/hugo/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/hugo.svg alt=hugo>
</a><a href=quickstart/jekyll/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/jekyll.svg alt=jekyll>
</a><a href=quickstart/netdata/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/netdata.webp alt=netdata>
</a><a href=quickstart/strapi/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/strapi.svg alt=strapi>
</a><a href=quickstart/jupyternotebook/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/jupyter.svg alt=jupyter>
</a><a href=quickstart/django/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/django.svg alt=django>
</a><a href=quickstart/apachehttpd/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/apache.svg alt=apache>
</a><a href=quickstart/drupal/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/drupal.svg alt=drupal>
</a><a href=quickstart/flask/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/flask.svg alt=flask>
</a><a href=quickstart/github/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/github.svg alt=github>
</a><a href=quickstart/gitlab/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/gitlab.svg alt=gitlab>
</a><a href=quickstart/joomla/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/joomla.svg alt=joomla>
</a><a href=quickstart/laravel/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/laravel.svg alt=laravel>
</a><a href=quickstart/mongodb/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/mongodb.svg alt=mongodb>
</a><a href=quickstart/mysql/ class="ribbon-element text-decoration-none text-reset" target=_blank><img src=./quickstart/images/mysql.svg alt=mysql></a></div></div></div></section></div><div class=col-lg-6><div class=termgif-terminal><div class=termgif-header><div class=termgif-dots><div class="termgif-dot red"></div><div class="termgif-dot yellow"></div><div class="termgif-dot green"></div></div><span style="margin:0 auto;font-size:13px;color:#444;font-weight:500;letter-spacing:.2px;position:absolute;left:0;right:0;text-align:center">bash - pinggy</span></div><div class=termgif-content id=terminalContent></div></div></div></div></div><script>function renderTerminalContent(){const e=document.getElementById("terminalContent");e.innerHTML=`
    <div class="termgif-step" style="animation-delay: 0s;"><span style="color:#A6E22E;">$</span> ssh -p 443 -R0:localhost:3000 tok+qr@pro.pinggy.io</div>
    <div class="termgif-step" style="margin-top: 1em; animation-delay: 0.7s;"><span style="color:#ffffff;">You are authenticated as user@example.com</span><br><span style="color:#fffcd3;">https://myapp.a.pinggy.link</span></div>
    <div class="termgif-step" style="animation-delay: 1.5s; margin-top: 2em;"><span style="color: #2e8be2;">  GET </span><span style="color: #A6E22E;">200 OK      /index.html</span></div>
    <div class="termgif-step" style="animation-delay: 2s;"><span style="color: #2e8be2;">  GET </span><span style="color: #A6E22E;">200 OK      /_next/static/css/8b418144d8f6049f.css</span></div>
    <div class="termgif-step" style="animation-delay: 2.2s;"><span style="color: #2e8be2;">  GET </span><span style="color: #A6E22E;">200 OK      /icon.svg?d1cd45fef217606d</span></div>
    `}renderTerminalContent(),setInterval(renderTerminalContent,6e3)</script><section class=pt-5 id=features><div class="container my-5"><div class="row justify-content-evenly"><div class="col-lg-6 mb-5 mb-lg-0"><div class="videocontainer ratio ratio-16x9"><video preload=none onclick="this.paused&&!this.controls&&(this.controls=!0,this.play())" poster=/assets/tunnelvideothumb.webp>
<source src=/assets/pinggy_demo.webm type=video/webm>Your browser does not support HTML video.</video></div></div><div class="col-lg-4 mb-5 mb-lg-0"><div class="feature bg-subtlegray border-subtlegray text-gray rounded-3 mb-3"><i class="bi bi-collection"></i></div><h2 class="h3 fw-bolder">Share your websites and apps in seconds!</h2><ul class="list-unstyled text-muted"><li class=my-3><i class="bi bi-check2-circle me-2"></i> Skip uploading to cloud</li><li class=my-3><i class="bi bi-check2-circle me-2"></i> No need to download any
tool</li><li class=my-3><i class="bi bi-check2-circle me-2"></i> Link your own domain</li><li class=my-3><i class="bi bi-check2-circle me-2"></i> Basic Authentication</li></ul><a href=/quickstart/><button class="btn btn-primary me-2" style=background-color:#4675c7>
Quickstart
</button></a>
<a class="text-decoration-none pinggy-link" href=/docs/http_tunnels/>Learn more
<i class="bi bi-arrow-up-right-square"></i></a></div></div></div></section><section class="pt-5 mt-5" id=features><div class="container my-5"><div class="row justify-content-evenly"><div class="col-lg-4 mb-5 mb-lg-0"><div class="feature bg-subtlegray border-subtlegray text-gray rounded-3 mb-3"><i class="bi bi-bug"></i></div><h2 class="h3 fw-bolder">Debug on the go!</h2><ul class="list-unstyled text-muted"><li class=my-3><i class="bi bi-check2-circle me-2"></i> Debug HTTP / HTTPS requests
live</li><li class=my-3><i class="bi bi-check2-circle me-2"></i> No need to download any
tool</li><li class=my-3><i class="bi bi-check2-circle me-2"></i> Replay requests</li></ul><a class="text-decoration-none pinggy-link" href=/docs/http_tunnels/>Learn more
<i class="bi bi-arrow-up-right-square"></i></a></div><div class="col-lg-6 mb-5 mb-lg-0"><img src=/assets/webdebugger.webp class="img-fluid featureimage" alt="Pinggy web debugger screenshot"></div></div></div></section><section class="pt-5 mt-5" id=features><div class="container my-5"><div class="row justify-content-evenly"><div class="col-lg-6 mb-5 mb-lg-0"><div id=carouselTUI class="carousel slide" data-bs-ride=carousel><div class=carousel-inner><div class="carousel-item active" data-bs-interval=2000><img src=/assets/tui1.webp class="d-block w-100 img-fluid featureimage" alt="Pinggy terminal user interface (TUI) screenshot showing list of requests"></div><div class=carousel-item data-bs-interval=2000><img src=/assets/tui2.webp class="d-block w-100 img-fluid featureimage" alt="Pinggy terminal user interface (TUI) screenshot showing request and response headers of an HTTP request"></div></div><button class=carousel-control-prev type=button data-bs-target=#carouselTUI data-bs-slide=prev>
<span class=carousel-control-prev-icon aria-hidden=true></span>
<span class=visually-hidden>Previous</span>
</button>
<button class=carousel-control-next type=button data-bs-target=#carouselTUI data-bs-slide=next>
<span class=carousel-control-next-icon aria-hidden=true></span>
<span class=visually-hidden>Next</span></button></div></div><div class="col-lg-4 mb-5 mb-lg-0"><div class="feature bg-subtlegray border-subtlegray text-gray rounded-3 mb-3"><i class="bi bi-terminal"></i></div><h2 class="h3 fw-bolder">Rich Terminal Interface</h2><ul class="list-unstyled text-muted"><li class=my-3><i class="bi bi-check2-circle me-2"></i> Live request logs</li><li class=my-3><i class="bi bi-check2-circle me-2"></i> View request / response
headers</li><li class=my-3><i class="bi bi-check2-circle me-2"></i> Stats on bandwidth and more</li></ul><a class="text-decoration-none pinggy-link" href=/docs/http_tunnels/>Learn more
<i class="bi bi-arrow-up-right-square"></i></a></div></div></div></section><section class="py-5 border-bottom" id=features><div class="container my-5"><div class="my-3 row justify-content-center"><div class=col-lg-12><h2 class="text-center fw-light">Secure tunnels to your private network.</h2></div></div><div class="row justify-content-center"><div class=col-lg-8><img class=img-fluid src=/assets/header.webp alt="Pinggy tunnel network diagram showing how the tunnel works"></div></div></div></section><section class=border-bottom id=appcli><div class="container my-5"><div class="my-3 row justify-content-center"><div class=col-lg-12><h2 class=text-center>Easy to use apps</h2></div></div><div class="row justify-content-evenly"><div class="col-lg-5 mb-5 mb-lg-0"><h2 class="h3 fw-bolder mt-3">Desktop App</h2><ul class="list-unstyled text-muted"><li class=my-3><i class="bi bi-check2-circle me-2"></i> Available for Windows, Mac, and Linux</li><li class=my-3><i class="bi bi-check2-circle me-2"></i> Easy to use GUI to manage your tunnels</li><li class=my-3><i class="bi bi-check2-circle me-2"></i> Auto start tunnels on boot</li></ul><a class="text-decoration-none pinggy-link" href=/app/>Learn more
<i class="bi bi-arrow-up-right-square"></i></a><h2 class="h3 fw-bolder mt-5">Command Line App</h2><ul class="list-unstyled text-muted"><li class=my-3><i class="bi bi-check2-circle me-2"></i> Robust auto reconnection</li><li class=my-3><i class="bi bi-check2-circle me-2"></i> JSON configuration</li></ul><a class="text-decoration-none pinggy-link" href=/cli/>Learn more
<i class="bi bi-arrow-up-right-square"></i></a></div><div class="col-lg-6 mb-5 mb-lg-0"><a href=./app/><img src=/assets/app5.webp class="img-fluid featureimage my-4" alt="Pinggy desktop app screenshot"></a></div></div></div></section><section class="py-5 border-bottom" id=features><div class="container my-5"><div class="my-3 row justify-content-center"><div class=col-lg-12><h2 class="mb-5 text-center">Features</h2></div></div><div class=row><div class="col-lg-4 mb-5 mb-lg-0"><div class="card featurecard p-4"><div class="feature bg-subtlegray border-subtlegray text-gray rounded-3 mb-3"><i class="bi bi-window-stack"></i></div><h2 class="h3 fw-bolder">No downloads</h2><h2 class="h6 fw-light">Runs everywhere</h2><p><i class="bi bi-check2-circle me-2"></i><b>Windows</b><br><i class="bi bi-check2-circle me-2"></i><b>Mac</b><br><i class="bi bi-check2-circle me-2"></i><b>Linux</b><br><i class="bi bi-check2-circle me-2"></i><b>Docker</b></p></div></div><div class="col-lg-4 mb-5 mb-lg-0"><div class="card featurecard p-4"><div class="feature bg-subtlegray border-subtlegray text-gray rounded-3 mb-3"><i class="bi bi-hdd-network"></i></div><h2 class="h3 fw-bolder">Multiple Protocols</h2><p><i class="bi bi-check2-circle me-2"></i><b>HTTPS</b> tunnels with
built-in Let's Encrypt certificates for web applications.<br><i class="bi bi-check2-circle me-2"></i><b>TCP</b> tunnels for other applications.<br><i class="bi bi-check2-circle me-2"></i><b>UDP</b> tunnels.<br><i class="bi bi-check2-circle me-2"></i><b>TLS</b> tunnels for end-to-end encryption.</p></div></div><div class="col-lg-4 mb-5 mb-lg-0"><div class="card featurecard p-4"><div class="feature bg-subtlegray border-subtlegray text-gray rounded-3 mb-3"><i class="bi bi-link-45deg"></i></div><h2 class="h3 fw-bolder">Instant Domains</h2><p><i class="bi bi-check2-circle me-2"></i><b>Subdomain</b>: Custom persistent subdomains.<br><i class="bi bi-check2-circle me-2"></i><b>Custom domain</b>: Bring your own domains with built-in HTTPS
certificates.<br><i class="bi bi-check2-circle me-2"></i>
<b>Wildcard domains</b>: Use <code>*.yourdomain.com</code> to route different subdomains to different ports.</p></div></div><div class="col-lg-4 mb-5 mb-lg-0"><div class="card featurecard p-4"><div class="feature bg-subtlegray border-subtlegray text-gray rounded-3 mb-3"><i class="bi bi-shield-lock"></i></div><h2 class="h3 fw-bolder">Access Control</h2><p><i class="bi bi-check2-circle me-2"></i><b>Password</b> authentication with HTTP Basic authentication.<br><i class="bi bi-check2-circle me-2"></i><b>Bearer token</b> /
key based authentication.<br><i class="bi bi-check2-circle me-2"></i><b>IP whitelisting</b> for restricted access.</p></div></div><div class=col-lg-4><div class="card featurecard p-4"><div class="feature bg-subtlegray border-subtlegray text-gray rounded-3 mb-3"><i class="bi bi-bug"></i></div><h2 class="h3 fw-bolder">Inspect & Debug</h2><p><i class="bi bi-check2-circle me-2"></i><b>Live debugger</b>:
Inspect HTTP requests on the fly. View requests, responses, headers,
etc.<br><i class="bi bi-check2-circle me-2"></i><b>Header manipulation</b>: Change HTTP request headers before they
arrive at your server.</p></div></div><div class=col-lg-4><div class="card featurecard p-4"><div class="feature bg-subtlegray border-subtlegray text-gray rounded-3 mb-3"><i class="bi bi-globe-americas"></i></div><h2 class="h3 fw-bolder">Multiple Regions</h2><h2 class="h4 fw-light">Fast Tunnels</h2><div class=container><div class=row><div class=col-md-6><p id=loc1><i class="bi bi-check2-circle me-2"></i><b>USA</b><br><i class="bi bi-check2-circle me-2"></i><b>Europe</b><br><i class="bi bi-check2-circle me-2"></i><b>Asia</b></p></div><div class=col-md-6><p id=loc2><i class="bi bi-check2-circle me-2"></i><b>Brazil</b><br><i class="bi bi-check2-circle me-2"></i><b>Australia</b></p></div></div></div></div></div></div></div></section><header class="bg-light py-5" id=prices x-init=$store.location.detectCountry()><div class=container><div class="row justify-content-md-center"><div class=col-lg-12><div class="pricing-header p-3 pb-md-4 mx-auto text-center"><h1 class="text-bold fw-normal">Subscribe to the easiest localhost tunneling.</h1><p class=fs-5 style=color:#505050>Make your developement experience smoother by unlocking the full
potential of Pinggy.</p></div><main><div class="row justify-content-center text-left"><div class="mb-3 col-md-9"><label class="toggler toggler--is-active align-middle" id=filt-monthly>Monthly</label>
<label class=switch aria-label="Toggle between monthly and yearly plans"><input id=toggleswitch type=checkbox checked>
<span class="slider round"></span>
</label><label class="toggler align-middle" id=filt-hourly>Yearly</label><span class=align-middle style=color:#325795;font-size:.8em>
(Save upto 17%)</span></div></div><div class="row row-cols-1 row-cols-md-4 mb-3 text-center justify-content-center"><div class="col mb-4"><div class="pricecard card rounded-3 shadow-sm"><div class="card-header py-3"><h4 class="my-0 fw-normal">Free</h4></div><div class="card-body d-flex flex-column"><div><h1 class="card-title pricing-card-title"><span x-text=$store.location.currency></span> 0<small class="text-muted fw-light">/month</small></h1><span class="text-muted fw-light">Free for life</span></div><ul class="list-unstyled mt-3 mb-4 list-group text-left"><li class="list-group-item p-2">Single command tunneling</li><li class="list-group-item p-2">HTTP(S), TCP, UDP, TLS tunnels</li><li class="list-group-item p-2">Live header manipulation</li><li class="list-group-item p-2">Request-response inspection & replays
                   </li><li class="list-group-item p-2"><b>60 minutes tunnel timeout</b></li><li class="list-group-item p-2">Random subdomains</li><li class="list-group-item p-2">Unlimited Data Transfer</li></ul><a class=mt-auto href=https://dashboard.pinggy.io/><button type=button class="w-100 btn btn-lg btn-outline-pinggy">
Go to dashboard</button></a></div></div></div><div x-data="{ seatVal: 1 }" class="col mb-4"><div class="pricecard card rounded-3 shadow-sm"><div class="card-header py-3"><h4 class="my-0 fw-normal">Pro</h4></div><div class="card-body d-flex flex-column"><div style="max-width:140px;margin:0 auto"><div class="input-group seat-spinner"><span class=input-group-btn><button @click="seatVal = Math.max(1, parseInt(seatVal) - 1)" class="btn btn-outline-dark">
-
</button>
</span><input type=number x-model=seatVal class="form-control text-center" aria-label="Number of seats" x-on:input="seatVal = isNaN(parseFloat(seatVal)) 
                                                    || seatVal < 1 ? 1 : seatVal">
<span class=input-group-btn><button @click="seatVal = parseInt(seatVal) + 1" class="btn btn-outline-dark">
+</button></span></div><span>Seats</span></div><div class=yearly><h1 class="card-title pricing-card-title"><span x-text=$store.location.currency></span> <span x-text="$store.location.currency === 'INR' ? (204.89 * seatVal).toFixed(2) : (2.50 * seatVal).toFixed(2)" id=yearprice></span><small class="text-muted fw-light">/month</small></h1><span class="text-muted fw-light">(billed annually)</span></div><div class=monthly><h1 class="card-title pricing-card-title"><span x-text=$store.location.currency></span> <span x-text="$store.location.currency === 'INR' ? (245.87 * seatVal).toFixed(2) : (3.00 * seatVal).toFixed(2)" id=monthprice></span><small class="text-muted fw-light">/month</small></h1><span class="text-muted fw-light">(billed monthly)</span></div><template x-if="seatVal > 20"><div class="alert alert-info text-center my-2" role=alert><a href=/contact_us/ target=_blank><b>Contact us</b></a> to get volume discounts!</div></template><ul class="list-unstyled mt-3 mb-4 text-left list-group"><li class="list-group-item p-2 bg-light">Everything in Free plan</li><li class="list-group-item p-2"><b><span x-text=seatVal></span> Persistent tunnel<span x-show="seatVal > 1">s</span></b></li><li class="list-group-item p-2"><b><span x-text=seatVal></span> Custom subdomain<span x-show="seatVal > 1">s</span></b></li><li class="list-group-item p-2"><b><span x-text=seatVal></span> Custom domain<span x-show="seatVal > 1">s</span></b></li><li class="list-group-item p-2"><b><span x-text=seatVal></span> Persistent TCP/UDP port<span x-show="seatVal > 1">s</span></b></li><li class="list-group-item p-2"><b><span x-text=seatVal></span> Team<span x-show="seatVal > 1">s</span></b> <a href=/docs/teams/ target=_blank class=link-dark><i class="bi bi-info-circle"></i></a></li><li class="list-group-item p-2">Remote Device Management</li><li class="list-group-item p-2"><b>Wildcard Domain Support</b></li><li class="list-group-item p-2"><b>Unlimited Data Transfer</b></li><li class="list-group-item p-2">Priority mail / Discord support</li></ul><a x-show="seatVal > 1" class="mt-auto w-100 btn btn-lg btn-pinggy" id=checkout-and-portal-button href=https://dashboard.pinggy.io>Get Started</a>
<button x-show="seatVal == 1" type=button class="mt-auto w-100 btn btn-lg btn-pinggy" data-bs-toggle=modal data-bs-target=#trialModal id=trialModalButton>
<span>Start 7 Days Free Trial</span></button></div></div></div><div class="col mb-4"><div class="pricecard card rounded-3 shadow-sm border-gray"><div class="card-header py-3 text-white bg-gray border-gray"><h4 class="my-0 fw-normal">Enterprise</h4></div><div class="card-body d-flex flex-column"><div><a href=/contact_us/ class="text-decoration-none text-dark"><h1 class="card-title pricing-card-title">Contact Us</h1></a><span class="text-muted fw-light">contact@pinggy.io</span></div><ul class="list-unstyled mt-3 mb-4 list-group text-left"><li class="list-group-item p-2 bg-light"><b>Dedicated Servers</b> / On Premise</li><li class="list-group-item p-2"><b>Unlimited persistent tunnels</b></li><li class="list-group-item p-2"><b>Unlimited custom subdomains</b></li><li class="list-group-item p-2"><b>Unlimited custom domains</b></li><li class="list-group-item p-2"><b>Unlimited persistent TCP/UDP ports</b></li><li class="list-group-item p-2"><b>Unlimited Teams</b>
<a href=/docs/teams/ target=_blank class=link-dark><i class="bi bi-info-circle"></i></a></li><li class="list-group-item p-2"><b>API to monitor and manage tunnels</b>
<a href=/docs/api/api/ target=_blank class=link-dark><i class="bi bi-info-circle"></i></a></li><li class="list-group-item p-2">Priority Discord & Call Support</li></ul><a class="mt-auto w-100 btn btn-lg btn-pinggy" id=checkout-and-portal-button-1 href=/contact_us/>Contact Us</a></div></div></div></div></main></div></div></div></header><div class="modal fade" id=trialModal tabindex=-1 aria-labelledby=trialModalLabel aria-hidden=true><div class="modal-dialog modal-lg"><div class="modal-content px-2 pb-3"><div class=modal-header><span class=modal-title id=trialModalLabel>Start 7 Days Free Trial</span>
<button type=button class=btn-close data-bs-dismiss=modal aria-label=Close></button></div><div class="modal-body pt-4"><div style="margin-top:4em;max-width:28em;margin:0 auto"><div style=font-weight:500><span class=highlight>Free Pinggy Pro for
7 days:</div><div class="input-group mt-1"><input type=email class=form-control placeholder=Email aria-label=Email aria-describedby=button-addon2 id=trialemail2><div style=border-radius:.2em class=invalid-tooltip id=emailinvalidtooltip2>Please enter a valid email</div><button style="border-color:#4775c6;background-color:#4675c7;padding:.6em 1em;box-shadow:0 0 4px #a3599b8c;font-weight:500" class="btn btn-secondary" type=button id=button-addon2 onclick=starttrial2()>
Start Trial</button></div></div></div></div></div></div><section class=py-5 id=faq x-data="{ searchTerm: '' }"><div class=container><div class="my-3 row justify-content-center"><div class=col-lg-12><h2 class="mb-5 text-center fw-light">Frequently Asked Questions</h2></div></div><div class="row justify-content-center mb-3"><div class=col-lg-8><input type=text id=faqSearch class=form-control placeholder=Search... x-model=searchTerm></div></div><div class="row justify-content-center"><div class=col-lg-8><div class=accordion id=accordionFaq><div class=accordion-item x-show=$refs.faq2.innerText.toLowerCase().includes(searchTerm.toLowerCase())><h2 class=accordion-header id=headingPassword><button class="accordion-button collapsed" type=button data-bs-toggle=collapse data-bs-target=#collapsePassword aria-expanded=false aria-controls=collapsePassword>
It is asking for password.</button></h2><div id=collapsePassword class="accordion-collapse collapse" aria-labelledby=headingPassword data-bs-parent=#accordionFaq><div class=accordion-body x-ref=faq2><p>If the ssh command prompts you for a password you can just
press enter (a blank password). Or you can type in something
random and press enter.</p><div class="alert alert-dark bg-light bg-gradient">For long running tunnels with auto-reconnect, generate an ssh
key.<br><b>In your terminal / command prompt run:
<code>ssh-keygen</code></b><br>Press Enter key (Return key) till the command finishes.<br>After this the ssh command will no longer ask for a password.</div></div></div></div><div class=accordion-item x-show=$refs.faq2.innerText.toLowerCase().includes(searchTerm.toLowerCase())><h2 class=accordion-header id=windowslocalhost><button class="accordion-button collapsed" type=button data-bs-toggle=collapse data-bs-target=#collapsewindowslocalhost aria-expanded=false aria-controls=collapsewindowslocalhost>
On Windows tunnel cannot reach localhost</button></h2><div id=collapsewindowslocalhost class="accordion-collapse collapse" aria-labelledby=windowslocalhost data-bs-parent=#accordionFaq><div class=accordion-body x-ref=faq2><p>In windows, sometimes, the ssh tunnel cannot reach localhost because of some bug in the ssh client. <b>Replace <code>localhost</code> with <code>127.0.0.1</code> in your Pinggy command.</b></p><p>Example:</p><div class="alert alert-dark bg-light bg-gradient">ssh -p 443 -R0:127.0.0.1:8000 -L4300:127.0.0.1:4300 qr@a.pinggy.io</div></div></div></div><div class=accordion-item x-show=$refs.faq1.innerText.toLowerCase().includes(searchTerm.toLowerCase())><h2 class=accordion-header id=headingOne><button class="accordion-button collapsed" type=button data-bs-toggle=collapse data-bs-target=#collapseOne aria-expanded=false aria-controls=collapseOne>
The command uses SSH. Doesn't it open up my computer to threats?</button></h2><div id=collapseOne class="accordion-collapse collapse" aria-labelledby=headingOne data-bs-parent=#accordionFaq><div class=accordion-body x-ref=faq1><p>Pinggy relies on SSH remote port forwarding. The option
<code>-R 0:localhost:8000</code> in the command only implies
that connections to the public URL given by pinggy are
forwarded to your <code>localhost:8000</code>.</p><p class="alert alert-dark bg-light bg-gradient">No other port than the one specified by you can be accessed by
Pinggy or by anyone through the public URLs provided by
Pinggy.</p><p>You can read more about the <code>-R</code> option of openssh
client
<a href=https://man7.org/linux/man-pages/man1/ssh.1.html target=_blank>here</a>. If you are using a different ssh client, then refer to its
documentation.</p></div></div></div><div class=accordion-item x-show=$refs.faq3.innerText.toLowerCase().includes(searchTerm.toLowerCase())><h2 class=accordion-header id=headingServerLocation><button class="accordion-button collapsed" type=button data-bs-toggle=collapse data-bs-target=#collapseServerLocation aria-expanded=false aria-controls=collapseServerLocation>
Where are Pinggy servers located?</button></h2><div id=collapseServerLocation class="accordion-collapse collapse" aria-labelledby=headingServerLocation data-bs-parent=#accordionFaq><div class=accordion-body x-ref=faq3><p><code>a.pinggy.io</code> is routed to the Pinggy server
nearest to your location. Currently we have our servers in
USA, Europe, UK, Singapore, Brazil, and Australia.</p></div></div></div><div class=accordion-item x-show=$refs.faq4.innerText.toLowerCase().includes(searchTerm.toLowerCase())><h2 class=accordion-header id=headingTwo><button class="accordion-button collapsed" type=button data-bs-toggle=collapse data-bs-target=#collapseTwo aria-expanded=false aria-controls=collapseTwo>
The URL changes after I restart the tunnel.</button></h2><div id=collapseTwo class="accordion-collapse collapse" aria-labelledby=headingTwo data-bs-parent=#accordionFaq><div class=accordion-body x-ref=faq4><p>Pinggy's free plan has a tunnel timeout of 60 minutes. If the
tunnel is closed by you or reaches the time limit, starting a
new tunnel will generate a new URL.</p><p>To obtain a permanent or persistent URL, or to use your own
domain, you must subscribe to Pinggy Pro.</p></div></div></div><div class=accordion-item x-show=$refs.faq5.innerText.toLowerCase().includes(searchTerm.toLowerCase())><h2 class=accordion-header id=headingThree><button class="accordion-button collapsed" type=button data-bs-toggle=collapse data-bs-target=#collapseThree aria-expanded=false aria-controls=collapseThree>
Does it work on all platforms: Linux, Windows, Mac, and Android?</button></h2><div id=collapseThree class="accordion-collapse collapse" aria-labelledby=headingThree data-bs-parent=#accordionFaq><div class=accordion-body x-ref=faq5><p>Yes. Current versions of Windows, Mac, as well as almost all
Linux distributions come with openssh client pre-installed.
Therefore Pinggy will just work out of the box.</p><p>To learn more about using Pinggy on Android read our
<a href=https://pinggy.io/blog/host_website_on_android/ target=_blank>blog post.</a></p></div></div></div><div class=accordion-item x-show=$refs.faq6.innerText.toLowerCase().includes(searchTerm.toLowerCase())><h2 class=accordion-header id=headingFour><button class="accordion-button collapsed" type=button data-bs-toggle=collapse data-bs-target=#collapseFour aria-expanded=false aria-controls=collapseFour>
How to use TCP and TLS tunnels?</button></h2><div id=collapseFour class="accordion-collapse collapse" aria-labelledby=headingFour data-bs-parent=#accordionFaq><div class=accordion-body x-ref=faq6><p>You can use TCP and TLS tunnels for free with Pinggy. Click on
"Advanced Settings" on the top of the homepage, and select
TCP.</p></div></div></div><div class=accordion-item x-show=$refs.faq7.innerText.toLowerCase().includes(searchTerm.toLowerCase())><h2 class=accordion-header id=headingFive><button class="accordion-button collapsed" type=button data-bs-toggle=collapse data-bs-target=#collapseFive aria-expanded=false aria-controls=collapseFive>
My tunnel breaks or stops working after a few minutes.</button></h2><div id=collapseFive class="accordion-collapse collapse" aria-labelledby=headingFive data-bs-parent=#accordionFaq><div class=accordion-body x-ref=faq7><p>Read our guide on long running tunnels
<a href=https://pinggy.io/docs/guides/long_running_tunnels/ target=_blank>here</a>.</p></div></div></div><div class=accordion-item x-show=$refs.faq8.innerText.toLowerCase().includes(searchTerm.toLowerCase())><h2 class=accordion-header id=headingConnectionReset><button class="accordion-button collapsed" type=button data-bs-toggle=collapse data-bs-target=#collapseConnectionReset aria-expanded=false aria-controls=collapseConnectionReset>
I am getting Connection closed / Connection reset error.</button></h2><div id=collapseConnectionReset class="accordion-collapse collapse" aria-labelledby=headingConnectionReset data-bs-parent=#accordionFaq><div class=accordion-body x-ref=faq8><p>Make sure you do not add any arbitrary argument after the SSH command.</p><p>One common reason for this is that an existing tunnel
with the same token is active.</p><p><b>Terminate your existing tunnel with the same token.</b> You
can do so from the Active Tunnels option in the dashboard.</p><p>You can also use the <b>Force</b> option in the dashbaord.</p></div></div></div><div class=accordion-item x-show=$refs.faq9.innerText.toLowerCase().includes(searchTerm.toLowerCase())><h2 class=accordion-header id=headingSix><button class="accordion-button collapsed" type=button data-bs-toggle=collapse data-bs-target=#collapseSix aria-expanded=false aria-controls=collapseSix>
Can Pinggy read my data?</button></h2><div id=collapseSix class="accordion-collapse collapse" aria-labelledby=headingSix data-bs-parent=#accordionFaq><div class=accordion-body x-ref=faq9><p>Pinggy does read tunnel traffic for providing the Web Debugger
feature.</p><p><b>Use TLS tunnels for Zero trust mode</b>, where Pinggy
cannot read your data. In this case your traffic is end-to-end
encrypted.</p></div></div></div></div></div></div></div></section><footer class="pt-5 pb-4 bg-dark"><div class="container text-white"><div class=row><div class="col-lg-3 col-md-6 mb-2 border-end border-color-subtlegray"><h5 class=mb-2>Product</h5><ul class=list-unstyled><li class=mb-1><a href=/app/ target=_blank class="link-light text-decoration-none">Pinggy App</a></li><li class=mb-1><a href=/cli/ target=_blank class="link-light text-decoration-none">Pinggy CLI</a></li><li class=mb-1><a href=/docs/ target=_blank class="link-light text-decoration-none">Pinggy SSH</a></li><li class=mb-1><a href=/#prices target=_blank class="link-light text-decoration-none">Pricing</a></li></ul></div><div class="col-lg-3 col-md-6 mb-2 border-end border-color-subtlegray"><h5 class=mb-2>Comparisons</h5><ul class=list-unstyled><li class=mb-1><a class="link-light text-decoration-none" href=/compare/pinggy-vs-ngrok/ target=_blank>Pinggy vs Ngrok</a></li><li class=mb-1><a class="link-light text-decoration-none" href=/compare/pinggy-vs-localxpose/ target=_blank>Pinggy vs Localxpose</a></li><li class=mb-1><a class="link-light text-decoration-none" href=/compare/pinggy-vs-localtunnel/ target=_blank>Pinggy vs LocalTunnel</a></li><li class=mb-1><a class="link-light text-decoration-none" href=/compare/pinggy-vs-cloudflare-tunnel/ target=_blank>Pinggy vs Cloudflare</a></li></ul></div><div class="col-lg-3 col-md-6 mb-2 border-end border-color-subtlegray"><h5 class=mb-2>Company</h5><ul class=list-unstyled><li class=mb-1><a href=/about/ target=_blank class="link-light text-decoration-none">About Us</a></li><li class=mb-1><a href=/contact_us/ target=_blank class="link-light text-decoration-none">Contact Us</a></li><li class=mb-1><a href=/terms_of_service/ target=_blank class="link-light text-decoration-none">Terms of Service</a></li><li class=mb-1><a href=/privacy_policy/ target=_blank class="link-light text-decoration-none">Privacy Policy</a></li></ul><div class="d-flex gap-3 mt-3"><a href=https://www.linkedin.com/company/pinggy/ target=_blank class="link-light text-decoration-none"><i class="bi bi-linkedin" style=font-size:1.4em></i></a>
<a href=https://x.com/pinggyio target=_blank class="link-light text-decoration-none"><i class="bi bi-twitter" style=font-size:1.4em></i></a>
<a href=https://discord.com/invite/KX5DpTs3xx target=_blank class="link-light text-decoration-none"><i class="bi bi-discord" style=font-size:1.4em></i></a>
<a href=https://forum.pinggy.io/ target=_blank class="link-light text-decoration-none"><img src=/assets/pinggy_forum_logo.png alt="Pinggy Community Forum Logo" style=width:1.4em;filter:invert(1);vertical-align:middle></a></div></div><div class="col-lg-3 col-md-6 mb-2 border-end border-color-subtlegray"><h5 class=mb-2>Resources</h5><ul class=list-unstyled><li class=mb-1><a href=/docs/ target=_blank class="link-light text-decoration-none">Documentation</a></li><li class=mb-1><a href=/quickstart/ target=_blank class="link-light text-decoration-none">Quickstart Recipes</a></li><li class=mb-1><a href=/blog/ target=_blank class="link-light text-decoration-none">Blog</a></li><li class=mb-1><a href=/tools/ target=_blank class="link-light text-decoration-none">Tools</a></li><li class=mb-1><a href=/know_your_port/ target=_blank class="link-light text-decoration-none">Know Your Ports</a></li></ul></div></div><div class="text-center pt-4 mt-1 border-top border-color-subtlegray"><p class="m-0 text-white" id=copyrighttext>Copyright &copy; Pinggy 2025</p></div></div></footer><link as=style onload='this.onload=null,this.rel="stylesheet"' href=https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css rel=preload><noscript><link rel=stylesheet href=https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css></noscript><script>var date=new Date;document.getElementById("copyrighttext").innerHTML="Copyright&copy;&nbsp;&nbsp; Pinggy &nbsp;&nbsp;"+date.getFullYear()</script></body><script src=/js/bundle.min.6b32407615d774f60b41e65be9962c92ed9e41b4c2fbddd2c2ee267bd84757eb.js integrity="sha256-azJAdhXXdPYLQeZb6ZYsku2eQbTC+93Swu4me9hHV+s=" crossorigin=anonymous></script><script type=text/javascript>const tooltipTriggerList=[].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]')),tooltipList=tooltipTriggerList.map(function(e){const t=new bootstrap.Tooltip(e,{trigger:"manual"});let s,n;return e.addEventListener("mouseenter",function(){let o;clearTimeout(s),t.show(),o=e.getAttribute("aria-describedby"),n=document.querySelector(`#${o}`),n.addEventListener("mouseleave",function(){t.hide()})}),e.addEventListener("mouseleave",function(){s=setTimeout(function(){n.matches(":hover")||t.hide()},100)}),t})</script></html>